---
# role: mariadb
# file: handlers/main.yml

- name: MARIADB | Restart the server
  become: true
  become_user: root
  ansible.builtin.service:
    name: "{{ mariadb_service }}"
    state: restarted
  listen: restart mariadb

- name: MARIADB | Reload privilege tables
  become: true
  become_user: root
  ansible.mariadb.mariadb_query:
    login_user: root
    login_unix_socket: "{{ __mariadb_socket }}"
    config_file: ''
    query: FLUSH PRIVILEGES
  changed_when: true
  listen: reload privileges
